### ISSUE TITLE
TypeError converting an scVal to string

### ISSUE THREAD

**Issue by chatch** [chatch/stellarexplorer#574]
This was on futurenet, see the /tx endpoint at the bottom.

```
2023-12-30T18:48:02Z app[3d8d347b7d2789] sin [info]entry.server: handleError: error: {}
2023-12-30T18:48:02Z app[3d8d347b7d2789] sin [info]entry.server: handleError: stack: TypeError: Cannot convert undefined or null to object
2023-12-30T18:48:02Z app[3d8d347b7d2789] sin [info]    at Function.entries (<anonymous>)
2023-12-30T18:48:02Z app[3d8d347b7d2789] sin [info]    at jsNativeObjectValToString (/app/build/index.js:3531:39)
2023-12-30T18:48:02Z app[3d8d347b7d2789] sin [info]    at jsNativeValToString (/app/build/index.js:3529:240)
2023-12-30T18:48:02Z app[3d8d347b7d2789] sin [info]    at scValToString (/app/build/index.js:3536:10)
2023-12-30T18:48:02Z app[3d8d347b7d2789] sin [info]    at /app/build/index.js:4575:85
2023-12-30T18:48:02Z app[3d8d347b7d2789] sin [info]    at Array.map (<anonymous>)
2023-12-30T18:48:02Z app[3d8d347b7d2789] sin [info]    at invokeFunctionParamsRawtoRendered (/app/build/index.js:4574:113)
2023-12-30T18:48:02Z app[3d8d347b7d2789] sin [info]    at InvokeHostFunction (/app/build/index.js:4588:41)
2023-12-30T18:48:02Z app[3d8d347b7d2789] sin [info]    at Uc (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:70:44)
2023-12-30T18:48:02Z app[3d8d347b7d2789] sin [info]    at Xc (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:72:253)
2023-12-30T18:48:02Z app[3d8d347b7d2789] sin [info]GET /tx/c71476b85bf81c3596f815719f3aaeb292bde5a72e25440e5b8bdd9236bd1fcb 500 - - 1386.127 ms
```

**Comment by chatch** [comment]
Issue was the handling of ScVoid - possibly something has changed as these were previously working.  Anyway now it will display 'void'.
