### ISSUE TITLE
"serve" npm module 

### ISSUE THREAD

**Issue by chaseeb** [chatch/stellarexplorer#75]
i cloned the source and did everything exactly as described but keep getting this error.  just wondering if anyone else has ever run into it.

/usr/local/lib/node_modules/serve/bin/serve.js:32
const updateCheck = async isDebugging => {
                          ^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)

thanks

**Comment by chatch** [comment]
this project doesn't use serve.  are you trying to run the project?  if so follow the instructions under "start" here: https://github.com/chatch/stellarexplorer#development

**Comment by chaseeb** [comment]
thanks for the reply.  yeah i'm just trying to run it.  but the npm i &&
npm run build just builds the project.  after that it tells you to run
"serve -s build" to run it locally.

**Comment by chatch** [comment]
hi @chasseb, try just running "npm start" which will load it with a dev server.

as for serve I tried it myself and it worked fine.  looking at the error above possible your using an old node version that doesn't understand 'const'?  try a recent version of node if that's the case...

**Comment by chaseeb** [comment]
Again thanks for the reply.  I updated node and it worked perfectly !!!
